- hosts: MySQL app gitlab runner monitoring
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - Update
   - node_exporter

  environment:
     http_proxy: http://smartnethome.site:8118
     https_proxy: http://smartnethome.site:8118
